export const ORDER_DETAILS_SAVE = "SAVE";
export const ORDER_DETAILS_ADD = "ADD";
export const ORDER_DETAILS_DELETE = "DELETE";
export const ORDER_DETAILS_GET = "GET";
export const ORDER_DETAILS_CLEAR = "CLEAR";
export const ORDER_DETAILS_SET = "ORDER_DETAILS_SET";
export const SET_ORDER_DERAILS_BY_FIELD_NAME =
  "SET_ORDER_DERAILS_BY_FIELD_NAME";
export const SET_ORDER_DETAILS_BY_INDEX = "SET_ORDER_DETAILS_BY_INDEX";
export const DELETE_ORDER_DETAILS_BY_ID = "DELETE_ORDER_DETAILS_BY_ID";

export function saveOrderinfo() {
  return { type: ORDER_DETAILS_SAVE };
}
