export const INVENTORY_ADD = "ADD";
export const INVENTORY_DELETE = "DELETE";
export const INVENTORY_GET = "GET";
export const INVENTORY_CLEAR = "CLEAR";
export const INVENTORY_SET = "INVENTORY_ASSIGN";
export const SET_INVENTORY_BY_FIELD_NAME = "SET_INVENTORY_BY_FIELD_NAME";
export const SET_INVENTORY_BY_HSC_CODE = "SET_INVENTORY_BY_HSC_CODE";
